steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aml-dashboard:$BUILD_ID', '.']
    
  # Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aml-dashboard:$BUILD_ID']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'aml-dashboard'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aml-dashboard:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '900'
      - '--max-instances'
      - '3'
      - '--min-instances'
      - '0'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

# Build configuration
options:
  machineType: 'E2_HIGHCPU_8'
  diskSizeGb: 100

# Timeout for the entire build
timeout: '1200s'

# Images to be pushed to registry
images:
  - 'gcr.io/$PROJECT_ID/aml-dashboard:$BUILD_ID'